name: avm_juis

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/avm_juis.yml'
      - 'docs/juis/generate.sh'
  schedule:
    - cron: '30 16 * * 1-5'
  workflow_dispatch:

concurrency:
  group: avm_juis
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: write
    container:
#     image: ubuntu:20.04
#     image: freetzng/generate
      image: ghcr.io/freetz-ng/generate
      options: --user 1001:1001
    runs-on: ubuntu-latest
    if: github.repository == 'freetz-ng/freetz-ng'

    steps:

      - name: key
        id: key
        run: |
          export KEY="${GITHUB_WORKFLOW%-*}"
          echo "key=$KEY" >> $GITHUB_OUTPUT
          echo "################################################################" && bash -c "echo KEY=$KEY"

#     - name: update
#       run: apt-get -y update && apt-get -y upgrade && apt-get -y dist-upgrade
#
#     - name: install
#       run: |
#         DEBIAN_FRONTEND=noninteractive apt-get -y install \
#           git locales netcat curl bsdmainutils xxd libarchive-zip-perl
#
#     - name: locale
#       run: locale-gen en_US.utf8 && locale-gen de_DE.UTF-8 && update-locale

      - name: clone
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          set-safe-directory: true
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          path: ${{ github.workspace }}
          fetch-depth: 0
          clean: false
          persist-credentials: true

      - name: cache
        uses: actions/cache@v4
        if: always()
        with:
          path: /tmp/.freetz-juis
          key: ${{ steps.key.outputs.key }}-${{ github.run_id }}
          restore-keys: ${{ steps.key.outputs.key }}

      - name: generate
        run: |
          export LANG=en_US.utf8
          [ "${{ github.workflow }}" != "${{ steps.key.outputs.key }}" ] && c=5 || c=1
          seq $c | while read x; do docs/juis/generate.sh; done

      - name: censorship
        if: github.repository_owner == 'freetz-ng'
        run: sed -re 's,\.avm.\de/(.*(inhaus|labor).*),.example.com/\1,' -i docs/juis/README.md

      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git pull
          git add .
          git status
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git diff --cached --quiet && exit 0 || git commit -m "juis: automatic update"
          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
          git push origin $GITHUB_REF_NAME

#     - name: cache_clear
#       env:
#         ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
#         CACHE_KEY: ${{ steps.key.outputs.key }}
#       run: |
#         ASSETS="$(curl -s  -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $ACTIONS_TOKEN"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/repos/${{ github.repository }}/actions/caches")"
#         ASSID="$(echo "$ASSETS" | grep -B7 "\"key\": *\"${CACHE_KEY}\"" | sed -rn 's/ *"id": *([^,]*),*/\1/p')"
#         curl -sL -X DELETE -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $ACTIONS_TOKEN"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/repos/${{ github.repository }}/actions/caches/$ASSID" && echo "Deleted ASSID=${ASSID:-null} ..." || true
#     - name: cache_save
#       uses: actions/cache/save@v4
#       if: always()
#       with:
#         path: /tmp/.freetz-juis
#         key: ${{ steps.key.outputs.key }}


